/* Generated by re2c 1.0.1 on Wed Aug 16 13:25:36 2017 */
#line 1 "test.c"
#include <stdio.h>

#define T_BEGIN 0
#define T_NUMBER 1
#define T_LOWER_CHAR 2
#define T_UPPER_CHAR 3
#define T_EXIT 4
#define T_UNKNOWN 5
#define T_INPUT_ERROR 6
#define T_END 7
#define T_WHITESPACE 8

typedef struct _scanner {
  char *yy_cursor;
  int yy_state;
  char *yy_limit;
  char *yy_marker;
} Scanner;

Scanner scanner_globals;

#define YYCTYPE char
#define YYFILL(n)
#define STATE(name)  yyc##name
#define BEGIN(state) YYSETCONDITION(STATE(state))
#define LANG_SCNG(v) (scanner_globals.v)
#define SCNG    LANG_SCNG

#define YYGETCONDITION()  SCNG(yy_state)
#define YYSETCONDITION(s) SCNG(yy_state) = s
#define YYCURSOR  SCNG(yy_cursor)
#define YYLIMIT   SCNG(yy_limit)
#define YYMARKER  SCNG(yy_marker)

int scan(){
    
#line 40 "test1.c"
{
	YYCTYPE yych;
	switch (YYGETCONDITION()) {
	case yycINITIAL: goto yyc_INITIAL;
	case yycST_IN_SCRIPTING: goto yyc_ST_IN_SCRIPTING;
	}
/* *********************************** */
yyc_INITIAL:
	if ((YYLIMIT - YYCURSOR) < 5) YYFILL(5);
	yych = *YYCURSOR;
	switch (yych) {
	case '<':	goto yy5;
	default:	goto yy3;
	}
yy3:
	++YYCURSOR;
yy4:
#line 47 "test.c"
	{return T_INPUT_ERROR;}
#line 60 "test1.c"
yy5:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '?':	goto yy6;
	default:	goto yy4;
	}
yy6:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'p':	goto yy8;
	default:	goto yy7;
	}
yy7:
	YYCURSOR = YYMARKER;
	goto yy4;
yy8:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'h':	goto yy9;
	default:	goto yy7;
	}
yy9:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'p':	goto yy10;
	default:	goto yy7;
	}
yy10:
	++YYCURSOR;
#line 38 "test.c"
	{BEGIN(ST_IN_SCRIPTING); return T_BEGIN;}
#line 92 "test1.c"
/* *********************************** */
yyc_ST_IN_SCRIPTING:
	if ((YYLIMIT - YYCURSOR) < 5) YYFILL(5);
	yych = *YYCURSOR;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy16;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy19;
	case '?':	goto yy22;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':	goto yy23;
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy26;
	case 'e':	goto yy29;
	default:	goto yy14;
	}
yy14:
	++YYCURSOR;
yy15:
#line 46 "test.c"
	{return T_UNKNOWN;}
#line 172 "test1.c"
yy16:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy16;
	default:	goto yy18;
	}
yy18:
#line 40 "test.c"
	{return T_WHITESPACE;}
#line 187 "test1.c"
yy19:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy19;
	default:	goto yy21;
	}
yy21:
#line 39 "test.c"
	{return T_NUMBER;}
#line 208 "test1.c"
yy22:
	yych = *++YYCURSOR;
	switch (yych) {
	case '>':	goto yy30;
	default:	goto yy15;
	}
yy23:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':	goto yy23;
	default:	goto yy25;
	}
yy25:
#line 43 "test.c"
	{return T_UPPER_CHAR;}
#line 251 "test1.c"
yy26:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy27:
	switch (yych) {
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy26;
	default:	goto yy28;
	}
yy28:
#line 42 "test.c"
	{return T_LOWER_CHAR;}
#line 289 "test1.c"
yy29:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'x':	goto yy32;
	default:	goto yy27;
	}
yy30:
	++YYCURSOR;
#line 44 "test.c"
	{return T_END;}
#line 300 "test1.c"
yy32:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy33;
	default:	goto yy27;
	}
yy33:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy34;
	default:	goto yy27;
	}
yy34:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy26;
	default:	goto yy35;
	}
yy35:
#line 41 "test.c"
	{ return T_EXIT; }
#line 347 "test1.c"
}
#line 48 "test.c"

}

void print_token(int token) {
    switch (token) {
        case T_BEGIN: printf("%s\n", "T_BEGIN");break;
        case T_NUMBER: printf("%s\n", "T_NUMBER");break;
        case T_LOWER_CHAR: printf("%s\n", "T_LOWER_CHAR");break;
        case T_UPPER_CHAR: printf("%s\n", "T_UPPER_CHAR");break;
        case T_EXIT: printf("%s\n", "T_EXIT");break;
        case T_UNKNOWN: printf("%s\n", "T_UNKNOWN");break;
        case T_INPUT_ERROR: printf("%s\n", "T_INPUT_ERROR");break;
        case T_END: printf("%s\n", "T_END");break;
    }
}

int main(int argc, char* argv[])
{
    int token;
    BEGIN(INITIAL); //  全局初始化，需要放在scan调用之前
    scanner_globals.yy_cursor = argv[1];    //将输入的第一个参数作为要解析的字符串

    while(1) {
        if(*YYCURSOR == '\0') break;
        token = scan();
        print_token(token);
    }

    return 0;
}